name = "pinetask"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "pinetask-db"
database_id = "5e1b697b-a99d-4fb5-a2eb-c2bb2da9fc55"
